# Generated by Django 5.0.3 on 2024-03-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_medicamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentos',
            name='ingredientes',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
