# Generated by Django 5.0.3 on 2024-03-16 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_preciohmedicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioMedicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.medicamentos')),
                ('surcursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.surcursales')),
            ],
        ),
    ]
