# Generated by Django 5.0.3 on 2024-03-19 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_inventariomedicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteMedicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaVencimiento', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.medicamentos')),
            ],
        ),
    ]
