# Generated by Django 5.0.3 on 2024-03-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_lotemedicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
    ]
