# Generated by Django 5.0.3 on 2024-03-22 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_estadocompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraMedicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precioTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('fechaPedido', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaRecibido', models.DateField(blank=True, null=True)),
                ('fechaDespacho', models.DateField(blank=True, null=True)),
                ('numeroFactura', models.CharField(max_length=255)),
                ('estadoCompra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ecmedicamentos')),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.medicamentos')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.proveedores')),
            ],
        ),
        migrations.DeleteModel(
            name='EstadoCompra',
        ),
        migrations.AlterField(
            model_name='inventariomedicamento',
            name='surcursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.surcursales'),
        ),
        migrations.AlterField(
            model_name='lotemedicamento',
            name='medicamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.medicamentos'),
        ),
    ]
