# Generated by Django 5.0.3 on 2024-03-22 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_compramedicamento_delete_estadocompra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('compraMedicamentoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.compramedicamento')),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.medicamentos')),
            ],
        ),
    ]
