# Generated by Django 5.0.3 on 2024-03-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_compramedicamento_stock'),
    ]

    operations = [
    ]
