# Generated by Django 5.0.3 on 2024-03-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20240324_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
