# Generated by Django 5.0.3 on 2024-03-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_metodospago_alter_medicamentos_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariomedicamento',
            name='surcursal',
        ),
    ]
