# Generated by Django 5.0.3 on 2024-03-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_medicamentos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='fechaVencimiento',
            field=models.DateField(null=True),
        ),
    ]
