# Generated by Django 5.0.3 on 2024-03-24 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_tipodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('informacion', models.CharField(max_length=255)),
                ('tipodocumento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tipodocumento')),
            ],
        ),
    ]
