# Generated by Django 5.0.3 on 2024-04-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_proveedores_personaencargada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecmedicamentos',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
