# Generated by Django 5.0.3 on 2024-04-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_ecmedicamentos_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('informacion', models.CharField(max_length=255)),
            ],
        ),
    ]
