# Generated by Django 5.0.3 on 2024-04-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_cargos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargos',
            old_name='informacion',
            new_name='descripcion',
        ),
    ]
