# Generated by Django 5.0.3 on 2024-04-10 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_informacion_cargos_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('correoElectronico', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cargos')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.documento')),
            ],
        ),
    ]
