# Generated by Django 5.0.3 on 2024-04-11 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_empleados'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSalas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('surcursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.surcursales')),
                ('tipoSalas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tiposalas')),
            ],
        ),
    ]
