# Generated by Django 5.0.3 on 2024-04-12 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_tiposalas_salas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('correoElectronico', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='Genero')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.documento')),
            ],
        ),
    ]
