# Generated by Django 5.0.3 on 2024-04-13 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_citas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescripciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('indicaciones', models.TextField(blank=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('cita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.citas')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pacientes')),
            ],
        ),
    ]
