# Generated by Django 5.0.3 on 2024-04-13 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_prescripciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePrescripciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.medicamentos')),
                ('prescripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.prescripciones')),
            ],
        ),
    ]
