# Generated by Django 5.0.3 on 2024-04-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_detalleprescripciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescripciones',
            name='creado',
        ),
        migrations.AlterField(
            model_name='prescripciones',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
