# Generated by Django 5.0.3 on 2024-04-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_remove_prescripciones_creado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescripciones',
            name='paciente',
        ),
    ]
