# Generated by Django 5.0.3 on 2024-04-14 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_ordenesmedicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pacientes')),
            ],
        ),
    ]
