# Generated by Django 5.0.3 on 2024-04-14 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_historialclinico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialclinico',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.pacientes'),
        ),
    ]
