# Generated by Django 5.0.3 on 2024-04-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_remove_historialclinico_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuejasYSugerencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Queja', 'Queja'), ('Sugerencia', 'Sugerencia')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
