# Generated by Django 5.0.3 on 2024-04-16 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_quejasysugerencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cai', models.CharField(max_length=30)),
                ('rtn', models.CharField(max_length=30)),
                ('razonSocial', models.CharField(max_length=30)),
                ('nombreEmpresa', models.CharField(max_length=30)),
                ('rangoAutorizadoInicial', models.IntegerField()),
                ('rangoAutorizadoFinal', models.IntegerField()),
                ('fechaLimiteEmision', models.DateField()),
                ('fechaInicial', models.DateField()),
                ('correoElectronico', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('surcursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.surcursales')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('isv', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodoPago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.metodospago')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pacientes')),
                ('parametros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.parametros')),
            ],
        ),
    ]
