# Generated by Django 5.0.3 on 2024-04-16 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_parametros_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametros',
            name='fechaInicial',
        ),
        migrations.AddField(
            model_name='factura',
            name='numero',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.pacientes', unique=True),
        ),
    ]
