# Generated by Django 5.0.3 on 2024-04-16 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_remove_parametros_fechainicial_factura_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='surcursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.surcursales'),
        ),
    ]
