# Generated by Django 5.0.3 on 2024-04-16 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_factura_surcursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='surcursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.surcursales', unique=True),
        ),
    ]
