# Generated by Django 5.0.3 on 2024-04-16 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_remove_preciohmedicamento_medicamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentos',
            name='precio',
        ),
        migrations.AddField(
            model_name='preciohmedicamento',
            name='medicamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.medicamentos'),
        ),
    ]
