# Generated by Django 5.0.3 on 2024-04-16 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_remove_preciohmedicamento_fechafinal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentos',
            name='precio',
        ),
        migrations.AddField(
            model_name='preciohmedicamento',
            name='Medicamentos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.medicamentos'),
        ),
    ]
