# Generated by Django 5.0.3 on 2024-04-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_remove_preciohmedicamento_surcursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
