# Generated by Django 5.0.3 on 2024-04-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_medicamentos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciohmedicamento',
            name='fechaInicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
