# Generated by Django 5.0.3 on 2024-04-16 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_preciohmedicamento_fechainicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='medicamento',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.lotemedicamento'),
        ),
    ]
