# Generated by Django 5.0.3 on 2024-04-16 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_remove_detallepedido_medicamento_detallepedido_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='lote',
        ),
        migrations.AddField(
            model_name='lotemedicamento',
            name='detallePedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.detallepedido'),
        ),
    ]
