# Generated by Django 5.0.3 on 2024-04-17 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_remove_detallepedido_lote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotemedicamento',
            name='detallePedido',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.lotemedicamento'),
        ),
    ]
