# Generated by Django 5.0.3 on 2024-04-17 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_remove_lotemedicamento_detallepedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='fechaVencimiento',
        ),
        migrations.RemoveField(
            model_name='lotemedicamento',
            name='medicamento',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='medicamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.medicamentos'),
        ),
        migrations.AlterField(
            model_name='lotemedicamento',
            name='fechaVencimiento',
            field=models.DateField(null=True),
        ),
    ]
