# Generated by Django 5.0.3 on 2024-04-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_inventariomedicamento_lote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='medicamento',
        ),
        migrations.AlterField(
            model_name='lotemedicamento',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lotemedicamento',
            name='fechaVencimiento',
            field=models.DateField(),
        ),
    ]
