# Generated by Django 5.0.3 on 2024-04-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_remove_detallepedido_medicamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotemedicamento',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='lotemedicamento',
            name='fechaVencimiento',
            field=models.DateField(null=True),
        ),
    ]
