# Generated by Django 5.0.3 on 2024-04-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_remove_lotemedicamento_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotemedicamento',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
