# Generated by Django 5.0.3 on 2024-04-20 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_lotemedicamento_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotemedicamento',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.compramedicamento'),
        ),
    ]
