# Generated by Django 5.0.3 on 2024-04-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_lotemedicamento_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariomedicamento',
            name='lote',
        ),
    ]
