# Generated by Django 5.0.3 on 2024-04-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_remove_inventariomedicamento_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='estado',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
