# Generated by Django 5.0.3 on 2024-04-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_empleados_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
