# Generated by Django 5.0.3 on 2024-04-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_alter_empleados_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
