# Generated by Django 5.0.3 on 2024-04-22 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_citas_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCitas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='citas',
            name='precio',
        ),
        migrations.AddField(
            model_name='citas',
            name='tipocita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tipocitas'),
        ),
    ]
