# Generated by Django 5.0.3 on 2024-04-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_tipocitas_remove_citas_precio_citas_tipocita'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='rtn',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
