# Generated by Django 5.0.3 on 2024-04-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_alter_parametros_cai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='cai',
            field=models.CharField(max_length=35),
        ),
    ]
