# Generated by Django 5.0.3 on 2024-04-27 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_isv_alter_factura_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isv',
            old_name='precio',
            new_name='impuesto',
        ),
        migrations.AlterField(
            model_name='factura',
            name='isv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.isv'),
        ),
    ]
