# Generated by Django 5.0.3 on 2024-04-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_rename_precio_isv_impuesto_alter_factura_isv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isv',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
