# Generated by Django 5.0.3 on 2024-04-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_alter_isv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprescripciones',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
