# Generated by Django 5.0.3 on 2024-04-28 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_factura_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detallePrescripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.detalleprescripciones')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.factura')),
            ],
        ),
    ]
