# Generated by Django 5.0.3 on 2024-04-28 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_alter_factura_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='factura',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='cita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.citas'),
        ),
    ]
