# Generated by Django 5.0.3 on 2024-04-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_remove_detallefactura_factura_detallefactura_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
