# Generated by Django 5.0.3 on 2024-04-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_alter_factura_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescripciones',
            name='indicaciones',
            field=models.TextField(),
        ),
    ]
