# Generated by Django 5.0.3 on 2024-04-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_alter_prescripciones_indicaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesmedicas',
            name='indicaciones',
            field=models.TextField(),
        ),
    ]
