# Generated by Django 5.0.3 on 2024-04-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_alter_ordenesmedicas_indicaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='personaEncargada',
            field=models.CharField(max_length=255),
        ),
    ]
