# Generated by Django 5.0.3 on 2024-04-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_alter_surcursales_personaencargada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surcursales',
            name='personaEncargada',
        ),
    ]
