# Generated by Django 5.0.3 on 2024-04-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_remove_surcursales_personaencargada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surcursales',
            name='correoElectronico',
            field=models.EmailField(max_length=254),
        ),
    ]
